### ISSUE TITLE
Operations: Website: Architecture for Multilanguage Support

### ISSUE THREAD

**Issue by wynnmade** [Museum-of-Art-and-Digital-Entertainment/MADE-Initiatives#65]

**Comment by PGrad** [comment]
This work is being tracked by GitHub issue [509](https://github.com/Museum-of-Art-and-Digital-Entertainment/made_deploy/issues/509) on the repo.

**Comment by PGrad** [comment]
That Github issue is closed now, but as @wynnmade, Pranav and I were discussing today, there's still plenty of work to be done on translation. Through issue #85, Pranav is going to discover and define the structure of the data that we're passing to our pages, which will also to find what fields can be translated and which cannot. I can do automatic translation of the data which we know needs to be translated, which will make it easier for expert translators to translate content later on.

We want to target translation for the communities which need it the most, which happen to be immigrant communities with a higher percentage of people that cannot speak English. As Shem said, we don't want a kid to not be able to come to a class because their parents can't speak English. In particular, we'd want to target these languages:
- Spanish
- [Hmong](https://en.wikipedia.org/wiki/Hmong_language)
- Tigrinya ([Eritrean](https://en.wikipedia.org/wiki/Languages_of_Eritrea#:~:text=The%20main%20languages%20spoken%20in,are%20Tigrinya%2C%20Arabic%2C%20English.&text=Tigrinya%20is%20the%20most%20widely,population%20of%205%2C254%2C000%20in%202006.))
- [Yemeni Arabic](https://en.wikipedia.org/wiki/Yemeni_Arabic)

Another part of this project then is to find native speakers who can provide expert translation in these languages.

**Comment by PGrad** [comment]
The Spanish version of the website is now appearing on Google:
<img width="864" alt="Screenshot 2024-06-17 at 5 49 57 PM" src="https://github.com/Museum-of-Art-and-Digital-Entertainment/MADE-Initiatives/assets/117248915/173ab6af-24f8-4d5a-b4e0-1ad7381dfff9">

It's pretty barebones, and doesn't show the sub-pages like the English search result does. It also seems to not match on keywords, like "the made" or "made oakland". I could look into why, but I think the higher priority item is to do automatic translation of our json files to the above languages. I can take a look into doing a small example for a page.
